# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eigen Method
email: your-email@domain.com
description: > # Site of Eigen Method, we are awesome guys, lets create software together!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eigenmethod.com"
twitter_username: eigen
github_username:  eigen

# Build settings
markdown: kramdown
